apiVersion: v1
kind: Service
metadata:
  name: python-api-svc
spec:
  # Esto creará un Classic Load Balancer en AWS automáticamente
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000